server:
    port: 8080
    servlet:
        context-path: /it
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/blog_db_v2
        username: root
        password: admin@123123

mybatis:
    type-aliases-package: edu.agic.itblog.entity
    mapper-locations: classpath:edu/agic/itblog/mapper/*Mapper.xml

uploadFile:
    location: D:/IdeaProject/itblog/src/main/resources/upload